Support different API versions of ingress
andersinno/kolga pull request #18
Opened 2021-05-03 06:01 UTC by Hi-Fi

Fixes #17

# Does this PR meet the acceptance criteria

* **Changelog**
    * [x] Changelog entry included
    * [ ] Changelog entry not needed
* **Documentation**
    * [ ] Documentation included
    * [x] Documentation not needed
* **Tests**
    * [ ] Tests included
    * [x] Tests not needed

2021-06-10 04:08 UTC, Hi-Fi commented
@frwickst How about this? Without the change update to Kubernetes 1.22 is not possible (that would be available e.g. in Azure at October and in GCP at August). Of course 1.21 EOL would be around next year summer, but it would be a bit hassle to have to update multiple versions at once if change comes later.

2021-06-29 11:02 UTC, frwickst requested changes
Thank you @Hi-Fi !
I totally missed this one, I'm really sorry. Need to check that our Slack integration is properly set up in the future so that i don't miss your contributions :D

2021-06-29 11:02 UTC, frwickst commented on helm/templates/05-ingress.yaml
> +{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
Could this be just `{{- if $stableApi -}}` ?

2021-06-29 14:35 UTC, Hi-Fi commented on helm/templates/05-ingress.yaml
> +{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
I think yes, can't remember at least directly if there was some issues with the variable.

2021-10-04 10:06 UTC, merged